#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xsetroot -cursor_name left_ptr

#xrandr --listproviders
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
# xrandr --auto --output HDMI-0 --mode 1920x1080
# xrandr --auto --output eDP-1-1 --right-of HDMI-0
xbindkeys

picom --backend glx & #--config ~/.dotfiles/picom.conf & #--experimental-backends &
#slstatus &
#feh --bg-center /home/flowey/.dotfiles/wallpaper.jpeg &
#./.startup-launch-apps.sh
# xrandr --auto --output eDP-1-1 --primary


# xmonad

dwm #>> dwm.log 
